language: nix

before_install:
  - ./.travis/configure-nix.sh
  - ./.travis/install-new-nix.sh

# Force VM instead of container, so that sandbox works
sudo: required

script:
  - nix build use_curl_release -o release-tests
  - nix build use_curl_fix1 -o fix1-tests
  - nix build use_curl_git -o git-tests
  - ./run.sh
